name: push@dev
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror repository
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
          source-repo: 'https://dev.fron.io/s/bqv/r/nixrc'
          destination-repo: 'git@github.com:bqv/nixrc.git'
